Allow for multiple configure attempts. - The previous code would prematurely abort after the first configure failed.

diff --git a/tools/mkws b/tools/mkws
--- a/tools/mkws
+++ b/tools/mkws
@@ -152,7 +152,7 @@ done
 
 export OPENSSL_ppccap=0
 
-multistrap -d "${WS_ROOT}" -f "${CONF}"
+multistrap -d "${WS_ROOT}" -f "${CONF}" || true
 
 rm -f "${CONF}"
 
@@ -174,8 +174,13 @@ echo "localhost" >/etc/hostname
 echo "en_US.UTF-8 UTF-8" >/etc/locale.gen
 /usr/sbin/locale-gen
 update-locale LANG=en_US.UTF-8
-dpkg --configure -a
-dpkg --configure -a # configure any packages that failed the first time
+
+#
+# Try to configure twice
+#
+dpkg --configure -a || true
+dpkg --configure -a # configure any packages that failed the first time and abort on failure. 
+
 rm -f /usr/sbin/policy-rc.d
 EOF
 chmod +x "${WS_ROOT}/tmp/config.sh"
