Evolve.

diff --git a/components/all/ztn/src/bin/ztn b/components/all/ztn/src/bin/ztn
--- a/components/all/ztn/src/bin/ztn
+++ b/components/all/ztn/src/bin/ztn
@@ -7,84 +7,221 @@
 #
 ############################################################
 
-# Import the ZTN library
-. /lib/ztn/ztn-functions
+SERVER=
+MAC=
+PLATFORM=
+SERIAL=
+URL=
+ZTN_ROOT=
+ZTN_FUNCTIONS=
+INTF=
+DISCOVER=
+MANIFEST=
+OPERATIONS=
 
-MODE=""
+__help__="
+Usage: $0 [OPTIONS] [OPERATIONS]
 
-# This script has to be invoked with either -discover or -url
-case "$1" in
-    -discover)
-        MODE="discover"
-        shift
-        intf=${1-ma1}
-    ;;
+Operations:
+  --discover: Run full ZTN discovery.
+  --manifest: Process a manifest URL.
+  --add-swi URL:  Add the given SWI URL to the cache.
+  --add-startup URL: Add the given startup-config URL to the cache.
+  --validate current|[manifest]: Validate the current or given manifest.
+  --inventory: Show the cache inventory
 
-    -url)
-        MODE="url"
-        shift
-        url=$1
-        if [ ! ${url} ]; then
-            exit 1
-        fi
-    ;;
-    *)
-        echo "Unknown argument '$1'" >&2
-        exit 1
-    ;;
-esac
+Options:
+  --root PATH: Override the default ZTN root directory.
+  --lib PATH:  Use the given ZTN library.
+  --platform PLATFORM: Set the platform name.
+  --intf INTF: Set the interface name for discovery transactions.
+  --serial SERIAL: Set the serial number.
+  --mac MAC: Set the mac address.
+  --server SERVER: Set the server name.
+  --url URL: Set the manifest url. This will override all other settings.
+"
 
-if [ -z "$MODE" ]; then
-    echo "Must give -discover or -url" >&2
+while [ "${1#-}" != "$1" ]; do
+    case "$1" in
+        -x)
+            set -x
+            ;;
+        --discover)
+            DISCOVER=1
+            OPERATIONS="${OPERATIONS} discover"
+            ;;
+        --manifest)
+            MANIFEST=1
+            OPERATIONS="${OPERATIONS} manifest"
+            ;;
+        --validate)
+            shift
+            VALIDATE=$1
+            OPERATIONS="${OPERAIONS} validate"
+            ;;
+        --inventory)
+            INVENTORY=1
+            OPERATIONS="${OPERATIONS} inventory"
+            ;;
+        --url)
+            shift
+            URL=$1
+            ;;
+        --mac)
+            shift
+            MAC=$1
+            ;;
+        --server)
+            shift
+            SERVER=$1
+            ;;
+        --platform)
+            shift
+            PLATFORM=$1
+            ;;
+        --serial)
+            shift
+            SERIAL=$1
+            ;;
+        --root)
+            shift
+            # This is used directly by the ZTN function library.
+            ZTN_ROOT=$1
+            ;;
+        --lib)
+            shift
+            # Use this ZTN library
+            ZTN_FUNCTIONS=$1
+            ;;
+        --add-swi)
+            shift
+            ADD_SWI=$1
+            OPERATIONS="${OPERATIONS} add-swi"
+            ;;
+        --add-startup)
+            shift
+            ADD_STARTUP=$1
+            OPERATIONS="${OPERATIONS} add-startup"
+            ;;
+        --intf)
+            shift
+            INTF=$1
+            ;;
+        -h|--help)
+            echo "${__help__}"
+            exit 0
+            ;;
+        *)
+	    echo "Unrecognized option $1" 2>&1
+	    exit 1
+	    ;;
+    esac
+    shift
+done
+
+
+if [ ! "${OPERATIONS}" ]; then
+    echo "No operation."
+    echo "${__help__}"
     exit 1
 fi
 
-# see if we are in (or if we want to be in) ZTN mode
-# retrieve the cached state of the previous swi
-swi_url_orig=$(sed -n -e 's/^SWI=\(.*\)/\1/p' /mnt/flash/boot-config)
-case "$swi_url_orig" in
-    "")
-        ZTN=1
-        swi_url_orig="flash2:.ztn-switchlight.swi"
-    ;;
-    flash2:.ztn-switchlight.swi)
-        ZTN=1
-    ;;
-    /mnt/flash2/.ztn-switchlight.swi)
-        ZTN=1
-        swi_url_orig="flash2:.ztn-switchlight.swi"
-    ;;
-esac
+#
+# Load the ZTN library
+#
+ZTN_FUNCTIONS=${ZTN_FUNCTIONS:-/lib/ztn/ztn-functions}
 
-if [ "$ZTN" ]; then
+if [ -e "${ZTN_FUNCTIONS}" ]; then
+    # Import the ZTN library
+    . ${ZTN_FUNCTIONS}
+else
+    echo "The ZTN library is missing. (${ZTN_FUNCTIONS})"
+    echo "You can specify its location with the --lib option."
+    exit 1
+fi
 
-    if [ -f /mnt/flash2/.ztn-switchlight.swi ]; then
-        swi_md5_orig=$(md5sum /mnt/flash2/.ztn-switchlight.swi 2>/dev/null | awk '{print $1}')
+#
+# Attempt some reasonable-ish defaults
+#
+if [ ! "${PLATFORM}" ]; then
+    if [ -e /etc/sl_platform ]; then
+        PLATFORM=$(cat /etc/sl_platform)
     fi
-
-    if [ -f /mnt/flash2/.ztn-startup-config ]; then
-        cfg_md5_orig=$(md5sum /mnt/flash2/.ztn-startup-config 2>/dev/null | awk '{print $1}')
+    if [ -e /etc/onl_platform ]; then
+        PLATFORM=$(cat /etc/onl_platform)
     fi
+fi
+SERIAL=${SERIAL:-unknown}
+INTF=${INTF:-ma1}
+MAC=${MAC:-$(ifconfig ${1} | awk '/HWaddr/ { print tolower($5) }')}
 
-    if [ "$MODE" = "discover" ]; then
-        echo "ZTN discover image from neighbor discovery"
-        macaddr=$(ifconfig ${intf} | awk '/HWaddr/ { print tolower($5) }')
-        platform=$(cat /etc/sl_platform)
-        ping6 -I ${intf} -c 3 ff02::1 > /dev/null 2>&1
-        neighs6=$(ip -6 neigh show | awk '{printf("%s%%'$intf'\n", $1)}')
 
-        ping -I ${intf} -w 2 -c 3 -q 255.255.255.255 > /dev/null 2>&1
-        neighs=$(ip -4 neigh show | awk '{print $1}')
+#
+# Perform whatever operations were requested.
+#
+if [ "${ADD_SWI}" ]; then
+    ztn_cache_install_url swi "${ADD_SWI}"
+fi
 
-        for a in $neighs6 $neighs; do
-            # XXX roth -- also add serial if available
-            url="http://${a}/ztn/switch/${macaddr}/switch_light_manifest?platform=${platform}"
-            dsc_swi_manifest ${url} && exit
-        done
+if [ "${ADD_STARTUP}" ]; then
+    ztn_cache_install_url startup-config "${ADD_STARTUP}"
+fi
 
-    elif [ "$MODE" = "url" ]; then
-        echo "ZTN precache image from url"
-        dsc_swi_manifest ${url}
-    fi 
+if [ "${VALIDATE}" ]; then
+    if [ "${VALIDATE}" = "current" ]; then
+        ztn_manifest_validate
+    else
+        ztn_manifest_validate "${VALIDATE}"
+    fi
+fi
 
+if [ "${INVENTORY}" ]; then
+    ztn_cache_inventory
+fi
+
+if [ "${MANIFEST}" ]; then
+    if [ "${URL}" ]; then
+        if ! ztn_manifest_process_url "${URL}"; then
+            echo "Failed."
+            exit 1
+        fi
+    else
+        if [ ! "${SERVER}" ]; then
+            echo "--server or --url must be set with --manifest."
+            exit 1
+        fi
+        if [ ! "${MAC}" ]; then
+            echo "--mac or --url must be set with --manifest."
+            exit 1
+        fi
+        if [ ! "${PLATFORM}" ]; then
+            echo "--platform or --url must be set with --manifest."
+            exit 1
+        fi
+        if [ ! "${SERIAL}" ]; then
+            echo "--serial or --url must be set with --manifest."
+            exit 1
+        fi
+        if ! ztn_manifest_process "${SERVER}" "${MAC}" "${PLATFORM}" "${SERIAL}"; then
+            echo "Failed."
+            exit 1
+        fi
+    fi
+fi
+
+
+
+
+if [ "${DISCOVER}" ]; then
+    if [ "${PLATFORM}" ]; then
+        # Intentionally test both library functions
+        if [ "${MAC}" ]; then
+            ztn_discovery_ex ${INTF} ${MAC} ${PLATFORM} ${SERIAL}
+        else
+            ztn_discovery ${INTF} ${PLATFORM} ${SERIAL}
+        fi
+    else
+        echo "Must specify --platform with --discover."
+        exit 1
+    fi
 fi
